# Generated by Django 2.1.15 on 2022-01-05 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_recipe_imapge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='imapge',
            new_name='image',
        ),
    ]
